# Get Twitter app credentials by creating a new app at
# https://apps.twitter.com/, which will show you the app key and
# app secret. You can also generate and Oauth token and secret
# on that page, or use Twython to authenticate.
twitter_app_key: ''
twitter_app_secret: ''
twitter_oauth_token: ''
twitter_oauth_token_secret: ''

# Pick a file name for the sqlite3 database of article metadata the bot gathers.
db: ''

# Pick a short descriptive user-agent for your bot for when it hits news sites.
# Some news sites will block the standard requests UA, so fill this out!
user-agent: ''

# Fill out all these fields and then rename this file config.yaml :)
